spring:
  application:
    name: Kata Agregio Solutions

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jmeritte
    username: sa
    password: ""
  jpa:
    properties:
      hibernate: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      data-locations: classpath:data/data.sql