erDiagram
    m[Marche] {
        int id
        String nom
    }
    o[Offre] {
        int id
    }
    m ||--o{ o: place
    o |o--|{ b: possede
    b[Bloc] {
        int id
        int quantiteEnergieMW
        BigDecimal prixPlancher
        int positionJournee
        Date jour
    }
    p[Parc] {
        int id
        int type
        int capaciteHoraireMW
    }
    a[AllocationParc] {
        int id
        int quantite
    }
    b }|--o{ a: alloue
    p }|--o{ a: produit
